import { StyleSheet } from "react-native";

export const styles = StyleSheet.create({
    container: {

    },
    barContainer: {
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'space-between',
        width: '95%',
        height: 45,
        backgroundColor: 'black',
        borderRadius: 10,
        marginTop: 10,
        marginLeft: 10,
    },
    return: {
        width: 80,
        backgroundColor: 'white',
        height: 25,
        borderRadius: 12,
        marginLeft: 10,
    },
    returnText: {
        textAlign: 'center',
        marginTop: 3,
    },
    icon: {
        flexDirection: 'row',
        marginRight: 5,

    },
    questions: {
        color: 'white',
        fontSize: 23,
        fontWeight: 'bold',
        marginLeft: 5,
    },
    squareContainer: {
        marginTop: 15,
        alignItems: "center",
    },
    square: {
        width: '95%',
        height: 150,
        backgroundColor: "#D9D9D9",
        justifyContent: "flex-start",
        alignItems: "flex-start",
        borderRadius: 10,
        marginBottom: 10,
        shadowColor: 'gray',
        shadowOffset: { width: 0, height: 2 },
        shadowOpacity: 5,
        shadowRadius: 1,
        elevation: 5,
    },
    squareText: {
        fontSize: 25,
        marginLeft: 10,
        marginTop: 10,
        fontWeight: 'bold',
    },
    squareWithCircles: {
        width: '95%',
        height: 'auto',
        alignItems: "center",
        backgroundColor: '#D9D9D9',
        shadowColor: 'gray',
        shadowOffset: { width: 0, height: 2 },
        shadowOpacity: 5,
        shadowRadius: 1,
        elevation: 5,
        borderRadius: 10,
        marginBottom: 12,
    },
    title: {
        fontSize: 20,
        fontWeight: "bold",
        marginBottom: 10,
        marginTop: 10,
    },
    circleContainer: {
        flexDirection: "column",
        alignItems: "flex-start",
        marginBottom: 10,

    },
    circle: {
        width: 350,
        height: 44,
        borderRadius: 10,
        backgroundColor: "#D9D9D9",
        marginVertical: 5,
        justifyContent: "center",
        alignItems: "center",
        borderWidth: 2,
        borderColor: "black",
    },
    circleText: {
        color: "black",
        fontSize: 18,
        fontWeight: 'bold',
        textAlign: 'left',
    },
    bottomSquareContainer: {
        marginTop: 12,
        alignItems: "center",
        width: '100%',
        marginBottom: 15,
    },
    bottomSquare: {
        width: '95%',
        backgroundColor: "#D9D9D9",
        borderRadius: 10,
        marginBottom: 12,
        padding: 10,
        shadowColor: 'gray',
        shadowOffset: { width: 0, height: 2 },
        shadowOpacity: 5,
        shadowRadius: 1,
        elevation: 5,
    },
    bottomSquareTitle: {
        fontSize: 20,
        fontWeight: "bold",
    },
    bottomSquareTextContainer: {
        marginTop: 10,
        backgroundColor: 'white',
        height: 70,
        borderRadius: 10,
        borderWidth: 1,
        borderColor: 'gray',
    },
    bottomSquareText: {
        fontSize: 18,
        padding: 5,
    },
    bottomSquareSubText: {
        fontSize: 12,
        padding: 5,
        color: 'gray',
        fontStyle: 'italic',
    },
    sliderContainer: {
        flexDirection: "row",
        alignItems: "center",
        marginTop: 10,
    },
    slider: {
        flex: 1,

    },
    sliderValue: {
        width: 50,
        textAlign: "center",
        fontSize: 20,
        color: 'white',
    },
    goalContainer: {
        backgroundColor: '#65D737',
        borderWidth: 2,
        borderColor: 'black',
        borderRadius: 8,
        height: 35,
        width: 60,
        marginLeft: 5,
        marginRight: 10,
        fontWeight: 'bold',
        justifyContent: 'center',
        alignItems: 'center'
    },
    circleContent: {
        flexDirection: 'row',
        justifyContent: 'space-between',
        alignItems: 'center',
        width: '100%',
        padding: 10,  
    },
    confirmButton: {
        backgroundColor: '#EBEBEB',
        borderRadius: 20,
        marginTop: 5,
        padding: 10,
        marginBottom:20,
        alignItems: 'center',
        justifyContent: 'center',
        width:'50%',
        marginLeft:'25%',
        shadowColor: 'black',
        shadowOffset: { width: 0, height: 2 },
        shadowOpacity: 5,
        shadowRadius: 1,
        elevation: 5,
    },
    confirmButtonText: {
        color: 'black',
        fontWeight: 'bold',
        fontSize:15,
    },
    checkboxesContainer: {
        flexDirection:'row',
        backgroundColor:"white",
        width:'95%',
        borderRadius:10,
        height:'auto',
        marginBottom:5,
        padding:5,
    },
    checkboxRow: {
        flexDirection: 'row',
        alignItems: 'center',
        marginBottom: 5,
    },
    checkboxLabel: {
        fontSize: 18,
        marginRight:15,

    },
    checkContainer: {
        backgroundColor:'#D9D9D9',
        flexDirection:'row',
        alignItems: 'center',
        marginRight:5,
        width: 'auto',
        height: '100%',
    }
});